# Helpers for starting Cursor agents from the command line.

function work() {
    local agent_path
    local issue_number
    local issue_key
    local agent_output
    local agent_status
    local prompt

    agent_path="$(command -v agent 2>/dev/null)"

    if [[ -z "$agent_path" ]]; then
        print -u2 "work: Cursor Agent CLI ('agent') is not installed or is not in PATH."
        print -u2 "Install it with: curl https://cursor.com/install -fsS | bash"
        return 127
    fi

    print "Cursor Agent CLI found: $agent_path"

    if (( $# != 1 )); then
        print -u2 "Usage: work <issue>"
        print -u2 "Example: work 1234"
        return 64
    fi

    if [[ "$1" == <-> ]]; then
        issue_number="$1"
    elif [[ "${1:u}" == TMU-<-> ]]; then
        issue_number="${1#*-}"
    else
        print -u2 "work: invalid issue '$1'; expected 1234, TMU-1234, or tmu-1234."
        return 64
    fi

    issue_key="TMU-$issue_number"
    print "Issue: $issue_key"

    if ! agent mcp list-tools linear >/dev/null 2>&1; then
        print -u2 "work: read-only Linear MCP ('linear') is not configured or authenticated."
        print -u2 "Configure it with: https://mcp.linear.app/mcp/readonly"
        return 69
    fi

    prompt="Use only the configured Linear MCP server's read-only tools to retrieve issue $issue_key.
Do not modify files, run shell commands, or create, update, or delete anything in Linear.
Print only the Git branch name generated by Linear for this issue (the gitBranchName field), with no label, Markdown, or explanation.
If the issue cannot be found, Linear MCP is unavailable, or the issue has no Git branch name, print one plain-text line beginning with 'work: error:'."

    agent_output="$(agent \
        --print \
        --mode=ask \
        --approve-mcps \
        --output-format text \
        "$prompt"
    )"
    agent_status=$?

    if (( agent_status != 0 )); then
        print -u2 "work: Cursor Agent failed while retrieving $issue_key."
        return "$agent_status"
    fi

    if [[ "$agent_output" == "work: error:"* ]]; then
        print -u2 "$agent_output"
        return 1
    fi

    if [[ -z "$agent_output" || "$agent_output" == *$'\n'* ]] ||
        ! git check-ref-format --branch "$agent_output" >/dev/null 2>&1; then
        print -u2 "work: Cursor Agent returned an invalid branch name for $issue_key."
        return 1
    fi

    print "Linear branch: $agent_output"
}
