# Helpers for starting TMU work in Cursor.

function tmu() {
    local agent_path
    local issue_number
    local issue_key
    local agent_output
    local agent_status
    local prompt
    local core_root
    local workspace
    local branch_name
    local worktree_path
    local desktop_prompt

    agent_path="$(command -v agent 2>/dev/null)"

    if [[ -z "$agent_path" ]]; then
        print -u2 "tmu: Cursor Agent CLI ('agent') is not installed or is not in PATH."
        print -u2 "Install it with: curl https://cursor.com/install -fsS | bash"
        return 127
    fi

    core_root="$(cd "$HOME/Code/bedrock/core" 2>/dev/null && pwd -P)"

    if [[ -z "$core_root" ]] ||
        [[ "$(git -C "$core_root" rev-parse --show-toplevel 2>/dev/null)" != "$core_root" ]]; then
        print -u2 "tmu: CORE repository is not available at $HOME/Code/bedrock/core."
        return 66
    fi

    workspace="$core_root"

    if (( $# != 1 )); then
        print -u2 "Usage: TMU <issue>"
        print -u2 "Examples: TMU 1234, TMU TMU-1234"
        return 64
    fi

    if [[ "$1" == <-> ]]; then
        issue_number="$1"
    elif [[ "${1:u}" == TMU-<-> ]]; then
        issue_number="${1#*-}"
    else
        print -u2 "tmu: invalid issue '$1'; expected 1234, TMU-1234, or tmu-1234."
        return 64
    fi

    issue_key="TMU-$issue_number"
    print "[linear] Looking up $issue_key..."

    if ! agent --workspace "$workspace" mcp list-tools linear >/dev/null 2>&1; then
        print -u2 "tmu: Linear MCP ('linear') is not configured or authenticated."
        print -u2 "Configure it with: https://mcp.linear.app/mcp"
        return 69
    fi

    prompt="Use only read operations from the configured Linear MCP server to retrieve issue $issue_key.
Do not modify files, run shell commands, or create, update, or delete anything in Linear.
Print only the Git branch name generated by Linear for this issue (the gitBranchName field), with no label, Markdown, or explanation.
If the issue cannot be found, Linear MCP is unavailable, or the issue has no Git branch name, print one plain-text line beginning with 'tmu: error:'."

    agent_output="$(agent \
        --print \
        --mode=ask \
        --workspace "$workspace" \
        --trust \
        --output-format text \
        "$prompt"
    )"
    agent_status=$?

    if (( agent_status != 0 )); then
        print -u2 "tmu: Cursor Agent failed while retrieving $issue_key."
        return "$agent_status"
    fi

    if [[ "$agent_output" == "tmu: error:"* ]]; then
        print -u2 "$agent_output"
        return 1
    fi

    if [[ -z "$agent_output" || "$agent_output" == *$'\n'* ]] ||
        ! git check-ref-format --branch "$agent_output" >/dev/null 2>&1; then
        print -u2 "tmu: Cursor Agent returned an invalid branch name for $issue_key."
        return 1
    fi

    branch_name="$agent_output"
    print "[linear] Branch: $branch_name"

    if (( ! $+functions[gwt] )); then
        print -u2 "tmu: gwt is unavailable; reload your Zsh configuration."
        return 127
    fi

    cd "$core_root" || {
        print -u2 "tmu: failed to enter the CORE repository."
        return 1
    }

    print "[worktree] Preparing CORE worktree..."

    gwt "$branch_name" || {
        print -u2 "tmu: failed to create or enter the CORE worktree."
        return 1
    }

    worktree_path="$(pwd -P)"

    if ! command -v code >/dev/null 2>&1; then
        print -u2 "tmu: the Cursor Desktop command ('code') is not available."
        print -u2 "Worktree ready at: $worktree_path"
        return 127
    fi

    code --new-window "$worktree_path" || {
        print -u2 "tmu: failed to open the worktree in Cursor Desktop."
        return 1
    }

    print "[cursor] Opened $worktree_path."

    desktop_prompt="Use Linear MCP to retrieve $issue_key and read its full description.
Confirm this worktree is on Linear's branch '$branch_name'.
Then inspect the repository, propose an implementation plan, and begin the issue."

    if command -v pbcopy >/dev/null 2>&1; then
        print -rn -- "$desktop_prompt" | pbcopy
        print "[prompt] Copied Agent prompt to the clipboard."
    else
        print "Start a new Agent chat with:"
        print "$desktop_prompt"
    fi
}

# Uppercase entry point matching the TMU product name.
function TMU() {
    tmu "$@"
}
