# Helpers for starting Cursor agents from the command line.

function work() {
    local agent_path
    local issue_number
    local issue_key
    local agent_output
    local agent_status
    local prompt
    local code_root
    local workspace
    local branch_name
    local worktree_path
    local desktop_prompt

    agent_path="$(command -v agent 2>/dev/null)"

    if [[ -z "$agent_path" ]]; then
        print -u2 "work: Cursor Agent CLI ('agent') is not installed or is not in PATH."
        print -u2 "Install it with: curl https://cursor.com/install -fsS | bash"
        return 127
    fi

    print "Cursor Agent CLI found: $agent_path"

    code_root="$(cd "$HOME/Code" 2>/dev/null && pwd -P)"
    workspace="$(pwd -P)"

    if [[ -z "$code_root" ]]; then
        print -u2 "work: $HOME/Code does not exist or cannot be accessed."
        return 77
    fi

    if [[ "$workspace" != "$code_root" && "$workspace" != "$code_root/"* ]]; then
        print -u2 "work: refusing to trust a workspace outside $code_root."
        return 77
    fi

    if (( $# != 1 )); then
        print -u2 "Usage: work <issue>"
        print -u2 "Example: work 1234"
        return 64
    fi

    if [[ "$1" == <-> ]]; then
        issue_number="$1"
    elif [[ "${1:u}" == TMU-<-> ]]; then
        issue_number="${1#*-}"
    else
        print -u2 "work: invalid issue '$1'; expected 1234, TMU-1234, or tmu-1234."
        return 64
    fi

    issue_key="TMU-$issue_number"
    print "Issue: $issue_key"

    if ! agent mcp list-tools linear >/dev/null 2>&1; then
        print -u2 "work: Linear MCP ('linear') is not configured or authenticated."
        print -u2 "Configure it with: https://mcp.linear.app/mcp"
        return 69
    fi

    prompt="Use only read operations from the configured Linear MCP server to retrieve issue $issue_key.
Do not modify files, run shell commands, or create, update, or delete anything in Linear.
Print only the Git branch name generated by Linear for this issue (the gitBranchName field), with no label, Markdown, or explanation.
If the issue cannot be found, Linear MCP is unavailable, or the issue has no Git branch name, print one plain-text line beginning with 'work: error:'."

    agent_output="$(agent \
        --print \
        --mode=ask \
        --workspace "$workspace" \
        --trust \
        --output-format text \
        "$prompt"
    )"
    agent_status=$?

    if (( agent_status != 0 )); then
        print -u2 "work: Cursor Agent failed while retrieving $issue_key."
        return "$agent_status"
    fi

    if [[ "$agent_output" == "work: error:"* ]]; then
        print -u2 "$agent_output"
        return 1
    fi

    if [[ -z "$agent_output" || "$agent_output" == *$'\n'* ]] ||
        ! git check-ref-format --branch "$agent_output" >/dev/null 2>&1; then
        print -u2 "work: Cursor Agent returned an invalid branch name for $issue_key."
        return 1
    fi

    branch_name="$agent_output"
    print "Linear branch: $branch_name"

    if (( ! $+functions[gwt] )); then
        print -u2 "work: gwt is unavailable; reload your Zsh configuration."
        return 127
    fi

    gwt "$branch_name" || {
        print -u2 "work: failed to create or enter the CORE worktree."
        return 1
    }

    worktree_path="$(pwd -P)"

    if ! command -v code >/dev/null 2>&1; then
        print -u2 "work: the Cursor Desktop command ('code') is not available."
        print -u2 "Worktree ready at: $worktree_path"
        return 127
    fi

    code --new-window "$worktree_path" || {
        print -u2 "work: failed to open the worktree in Cursor Desktop."
        return 1
    }

    desktop_prompt="Use Linear MCP to retrieve $issue_key and read its full description.
Confirm this worktree is on Linear's branch '$branch_name'.
Then inspect the repository, propose an implementation plan, and begin the issue."

    if command -v pbcopy >/dev/null 2>&1; then
        print -rn -- "$desktop_prompt" | pbcopy
        print "Agent prompt copied to the clipboard."
    else
        print "Start a new Agent chat with:"
        print "$desktop_prompt"
    fi
}
